import { useAuth } from "@workspace/replit-auth-web";
import { useGetMe } from "@workspace/api-client-react";
import { Link, useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { HeartPulse, ArrowRight, ShieldCheck, Activity, Users } from "lucide-react";
import { motion } from "framer-motion";
import { useEffect } from "react";
import { Skeleton } from "@/components/ui/skeleton";

export default function Landing() {
  const { user, isAuthenticated, isLoading, login } = useAuth();
  const { data: me, isLoading: isMeLoading } = useGetMe({
    query: { enabled: isAuthenticated }
  });
  const [, setLocation] = useLocation();

  useEffect(() => {
    if (isAuthenticated && me && !isMeLoading) {
      if (!me.role) {
        setLocation("/role-select");
      } else if (me.role === "patient") {
        if (!me.onboardingComplete) {
          setLocation("/onboarding");
        } else {
          setLocation("/dashboard");
        }
      } else if (me.role === "admin") {
        setLocation("/admin");
      }
    }
  }, [isAuthenticated, me, isMeLoading, setLocation]);

  if (isLoading || (isAuthenticated && isMeLoading)) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="flex flex-col items-center gap-4">
          <HeartPulse className="h-10 w-10 text-primary animate-pulse" />
          <Skeleton className="h-6 w-48" />
        </div>
      </div>
    );
  }

  if (isAuthenticated && me) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="flex flex-col items-center gap-4">
          <HeartPulse className="h-10 w-10 text-primary animate-pulse" />
          <p className="text-muted-foreground">Redirecting to your dashboard...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background flex flex-col font-sans">
      <header className="h-20 flex items-center justify-between px-6 md:px-12 max-w-7xl mx-auto w-full">
        <div className="flex items-center gap-2 font-serif font-semibold text-2xl text-primary">
          <HeartPulse className="h-8 w-8 text-primary" />
          RecoveryOS
        </div>
        <Button onClick={login} className="rounded-full px-6">
          Sign in
        </Button>
      </header>

      <main className="flex-1 flex flex-col items-center justify-center text-center px-4 py-20 max-w-5xl mx-auto w-full">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="max-w-3xl"
        >
          <h1 className="font-serif text-5xl md:text-7xl font-bold text-foreground leading-tight tracking-tight mb-6">
            Calm, focused recovery <br className="hidden md:block" />
            <span className="text-primary italic">tailored for you.</span>
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground mb-10 max-w-2xl mx-auto leading-relaxed">
            A modern rehabilitation platform connecting patients with AI-guided recovery plans, daily tracking, and clinical oversight.
          </p>
          <Button size="lg" onClick={login} className="rounded-full px-8 h-14 text-lg font-medium shadow-lg hover:shadow-xl transition-all">
            Get Started
            <ArrowRight className="ml-2 h-5 w-5" />
          </Button>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.2 }}
          className="mt-24 grid md:grid-cols-3 gap-8 text-left w-full"
        >
          <div className="bg-card p-8 rounded-3xl border shadow-sm">
            <div className="h-12 w-12 bg-primary/10 text-primary rounded-2xl flex items-center justify-center mb-6">
              <ShieldCheck className="h-6 w-6" />
            </div>
            <h3 className="text-xl font-semibold mb-3 font-serif">Smart Plans</h3>
            <p className="text-muted-foreground leading-relaxed">Personalized recovery schedules generated by advanced clinical AI, adapting to your progress.</p>
          </div>
          
          <div className="bg-card p-8 rounded-3xl border shadow-sm">
            <div className="h-12 w-12 bg-secondary/10 text-secondary rounded-2xl flex items-center justify-center mb-6">
              <Activity className="h-6 w-6" />
            </div>
            <h3 className="text-xl font-semibold mb-3 font-serif">Daily Tracking</h3>
            <p className="text-muted-foreground leading-relaxed">Log your pain levels and adherence seamlessly to see real trends over time.</p>
          </div>

          <div className="bg-card p-8 rounded-3xl border shadow-sm">
            <div className="h-12 w-12 bg-accent/50 text-primary rounded-2xl flex items-center justify-center mb-6">
              <Users className="h-6 w-6" />
            </div>
            <h3 className="text-xl font-semibold mb-3 font-serif">Clinical Oversight</h3>
            <p className="text-muted-foreground leading-relaxed">Clinicians get a birds-eye view of patient populations, spotting risk factors early.</p>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
