import { useGetMyRecoveryPlan, useGenerateMyRecoveryPlan, getGetMyRecoveryPlanQueryKey } from "@workspace/api-client-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Button } from "@/components/ui/button";
import { HeartPulse, Sparkles, RefreshCw, AlertTriangle, Shield, CheckCircle2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useQueryClient } from "@tanstack/react-query";
import { Link } from "wouter";

export default function PatientPlan() {
  const { data: plan, isLoading, error } = useGetMyRecoveryPlan();
  const generatePlan = useGenerateMyRecoveryPlan();
  const queryClient = useQueryClient();
  const { toast } = useToast();

  const handleRegenerate = async () => {
    try {
      await generatePlan.mutateAsync({});
      queryClient.invalidateQueries({ queryKey: getGetMyRecoveryPlanQueryKey() });
      toast({ title: "Plan regenerated successfully" });
    } catch (e: any) {
      if (e?.status === 402) {
        toast({
          title: "Upgrade Required",
          description: "You've hit your free limit for plan generations. Upgrade in Settings.",
          variant: "destructive",
          action: <Button variant="outline" size="sm" asChild><Link href="/settings">Upgrade</Link></Button>
        });
      } else {
        toast({ title: "Error regenerating plan", variant: "destructive" });
      }
    }
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <Skeleton className="h-10 w-64" />
        <Skeleton className="h-32 w-full" />
        <Skeleton className="h-64 w-full" />
      </div>
    );
  }

  if (!plan) {
    return (
      <div className="text-center py-20">
        <HeartPulse className="h-12 w-12 mx-auto text-muted-foreground mb-4 opacity-50" />
        <h2 className="text-xl font-medium mb-2">No active plan</h2>
        <p className="text-muted-foreground mb-6">Complete onboarding to generate your recovery plan.</p>
        <Button asChild><Link href="/onboarding">Complete Onboarding</Link></Button>
      </div>
    );
  }

  const { content } = plan;

  return (
    <div className="space-y-8 pb-10">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="font-serif text-3xl font-bold text-foreground">Your Recovery Plan</h1>
          <p className="text-muted-foreground flex items-center gap-2 mt-1">
            {plan.generatedBy === 'ai' ? (
              <><Sparkles className="h-4 w-4 text-primary" /> Generated by Clinical AI</>
            ) : (
              <><Shield className="h-4 w-4 text-primary" /> Customized by your Clinician</>
            )}
          </p>
        </div>
        <Button variant="outline" onClick={handleRegenerate} disabled={generatePlan.isPending}>
          <RefreshCw className={`h-4 w-4 mr-2 ${generatePlan.isPending ? 'animate-spin' : ''}`} />
          Regenerate Plan
        </Button>
      </div>

      <Card className="bg-primary/5 border-primary/20">
        <CardContent className="pt-6">
          <p className="text-lg leading-relaxed text-foreground">{content.summary}</p>
        </CardContent>
      </Card>

      <div className="grid md:grid-cols-2 gap-8">
        <div className="space-y-8">
          <section>
            <h2 className="text-xl font-serif font-semibold mb-4 flex items-center gap-2">
              <Activity className="h-5 w-5 text-primary" /> Recommended Exercises
            </h2>
            <div className="space-y-4">
              {content.exercises.map((ex, i) => (
                <Card key={i}>
                  <CardHeader className="pb-2">
                    <CardTitle className="text-base">{ex.name}</CardTitle>
                    <CardDescription>{ex.sets} sets × {ex.reps} reps • {ex.durationMinutes} min</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <p className="text-sm text-muted-foreground">{ex.instructions}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </section>
        </div>

        <div className="space-y-8">
          <section>
            <h2 className="text-xl font-serif font-semibold mb-4 flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-secondary" /> Lifestyle Tips
            </h2>
            <Card>
              <CardContent className="pt-6 space-y-3">
                {content.lifestyleTips.map((tip, i) => (
                  <div key={i} className="flex gap-3 text-sm text-muted-foreground">
                    <span className="text-secondary font-bold">•</span>
                    <span>{tip}</span>
                  </div>
                ))}
              </CardContent>
            </Card>
          </section>

          <section>
            <h2 className="text-xl font-serif font-semibold mb-4 flex items-center gap-2 text-destructive">
              <AlertTriangle className="h-5 w-5" /> Precautions
            </h2>
            <Card className="border-destructive/20 bg-destructive/5">
              <CardContent className="pt-6 space-y-3 text-destructive/90">
                {content.precautions.map((prec, i) => (
                  <div key={i} className="flex gap-3 text-sm">
                    <span className="font-bold">•</span>
                    <span>{prec}</span>
                  </div>
                ))}
              </CardContent>
            </Card>
          </section>
        </div>
      </div>

      <section>
        <h2 className="text-xl font-serif font-semibold mb-4">Weekly Schedule</h2>
        <div className="grid grid-cols-1 md:grid-cols-7 gap-4">
          {content.weeklyPlan.map((day, i) => (
            <Card key={i} className="bg-muted/30">
              <CardHeader className="p-4 pb-2">
                <CardTitle className="text-sm">{day.day}</CardTitle>
                <CardDescription className="text-xs">{day.focus}</CardDescription>
              </CardHeader>
              <CardContent className="p-4 pt-0">
                <ul className="text-xs text-muted-foreground space-y-1">
                  {day.activities.map((act, j) => (
                    <li key={j}>• {act}</li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>
    </div>
  );
}

// Quick component shim since lucide doesn't export Activity here in this scope easily without adding an import block above, adding it now:
import { Activity } from "lucide-react";
